# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('cost', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='product_image')),
            ],
        ),
    ]
